print("tuples and its operations")
number_tuple=(2,3,4,5,7)
print(number_tuple)
str_tuple=("amma , beema ,ceema, deema , emma ")
print(str_tuple)
mixed_tuple=number_tuple,str_tuple
print(mixed_tuple)
print("length:",len(number_tuple))
print("min:",min(number_tuple))
print("max:",max(number_tuple))
print("sum:",sum(number_tuple))
print("positive indexing")
print(number_tuple[0])
print(number_tuple[1])
print(number_tuple[2])
print(number_tuple[3])
print("negative indexing")
print(number_tuple[-1])
print(number_tuple[-2])
print(number_tuple[-3])
print("slicing")
print(number_tuple[0:3])
print(number_tuple[1:4])
print(number_tuple[2:5])
print("concantation:" , number_tuple,str_tuple)
print("nesting of tuple")
nested_tuple=(number_tuple,str_tuple,["iqu",48,5,2])
print("nested tuple")